#version 450

#define index gl_GlobalInvocationID.x

#define real double

layout (local_size_x = 64) in;

layout(binding = 0) buffer tempBuffer { real temp[]; };
layout(binding = 1) buffer rBuffer { real r[]; };
layout(binding = 2) buffer invDiagBuffer { real invDiag[]; };
layout(binding = 3) buffer restCoefBuffer { float restCoef[]; };

void main()
{
    temp[index] = temp[index] * restCoef[index] + r[index] * invDiag[index];
}