#version 450

#extension GL_EXT_shader_atomic_float: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable

#define index gl_GlobalInvocationID.x

#define real double

layout (local_size_x = 64) in;

layout(binding = 0) buffer x1Buffer { real x1[]; };
layout(binding = 1) buffer x2Buffer { real x2[]; };
layout(binding = 2) buffer normBuffer { real result; };

void main()
{
    real value = subgroupAdd(x1[index] * x2[index]);

    if(subgroupElect())
        atomicAdd(result, value);
}